[Statedef 12341234]
[State 12341234]
type=assertspecial
trigger1=1
flag=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA5"ปg5"ปgÿÿÿÿÿÿÿÿระปgÜปgธgฝg็:ธgโผgÿÿÿÿ฿ปgÿÿÿÿÿÿÿÿถบgระปg(ฝgถบgผgÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ฿ปgÿÿÿÿÿÿÿÿ6นgระปgÞÿÿ฿ปgÿÿÿÿÿÿÿÿwะนg๒หนgฝgp๖ผgÿÿÿÿ๚บg๚บgÿÿÿÿÿÿÿÿ็:ธgÿÿÿÿ฿ปgÿÿÿÿÿÿÿÿถบgฝะปgธgัkua๗,ผgผgÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿธg>"#ระปg--ÿ฿ปgÿÿÿÿÿÿÿÿwะนgถบgระปg$ฝgถบgผgÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿธg๒--’€บgลา$ำÿÿÿÿ–-ผgฝgธgฝgบgÿÿÿÿ|ฑำoถำÿÿÿÿธg----–-ผgฝg€บg๒หนgÿÿÿÿถบgฝะปgธgผฝgwะนgแปgÛ๖3cÿÿÿÿ5นgÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿธgฝg็:ธg